export const tables: { name: string; file: string; columns: [string, string][] }[] = [
    {
        name: `agency`,
        file: `agency.txt`,
        columns: [
            ["agency_id", "CITEXT PRIMARY KEY"],
            ["agency_name", "CITEXT"],
            // ["agency_url", "CITEXT"],
            // ["agency_timezone", "CITEXT"],
            // ["agency_lang", "CITEXT"],
            // ["agency_phone", "CITEXT"],
        ],
    },
    {
        name: `stops`,
        file: `stops.txt`,
        columns: [
            ["stop_id", "CITEXT PRIMARY KEY"],
            // ["stop_code", "CITEXT"],
            ["stop_name", "CITEXT"],
            // ["stop_desc", "CITEXT"],
            ["stop_lat", "DOUBLE PRECISION"],
            ["stop_lon", "DOUBLE PRECISION"],
            // ["zone_id", "CITEXT"],
            // ["stop_url", "CITEXT"],
            // ["location_type", "INT"],
            ["parent_station", "CITEXT"],
            // ["stop_timezone", "CITEXT"],
            // ["wheelchair_boarding", "SMALLINT"],
            // ["level_id", "CITEXT"],
            // ["platform_code", "CITEXT"],
        ],
    },
    {
        name: `routes`,
        file: `routes.txt`,
        columns: [
            ["route_id", "CITEXT PRIMARY KEY"],
            ["agency_id", "CITEXT"],
            ["route_short_name", "CITEXT"],
            ["route_long_name", "CITEXT"],
            ["route_desc", "CITEXT"],
            ["route_type", "INT"],
            ["route_url", "CITEXT"],
            ["route_color", "CITEXT"],
            ["route_text_color", "CITEXT"],
            // ["exact_times", "INT"],
        ],
    },
    {
        name: `trips`,
        file: `trips.txt`,
        columns: [
            ["route_id", "CITEXT"],
            ["service_id", "CITEXT"],
            ["trip_id", "CITEXT PRIMARY KEY"],
            ["shape_id", "CITEXT"],
            ["trip_headsign", "CITEXT"],
            ["trip_short_name", "CITEXT"],
            // ["direction_id", "BOOLEAN"],
            ["block_id", "CITEXT"],
            // ["wheelchair_accessible", "SMALLINT"],
            // ["route_direction", "CITEXT"],
            // ["trip_note", "CITEXT"],
            // ["bikes_allowed", "INT"],
            ["vehicle_category_id", "CITEXT"],
        ],
    },
    // {
    //     name: `notes`,
    //     file: `notes.txt`,
    //     columns: [
    //         ["note_id", "CITEXT PRIMARY KEY"],
    //         ["note_text", "CITEXT"],
    //     ],
    // },
    {
        name: `stop_times`,
        file: `stop_times.txt`,
        columns: [
            ["trip_id", "CITEXT"],
            ["arrival_time", "CITEXT"],
            ["departure_time", "CITEXT"],
            ["stop_id", "CITEXT"],
            ["stop_sequence", "SMALLINT"],
            ["stop_headsign", "CITEXT"],
            ["pickup_type", "INT"],
            ["drop_off_type", "INT"],
            // ["shape_dist_traveled", "DOUBLE PRECISION"],
            // ["timepoint", "INT"],
            // ["stop_note", "CITEXT"],
        ],
    },
    {
        name: `calendar`,
        file: `calendar.txt`,
        columns: [
            ["service_id", "CITEXT PRIMARY KEY"],
            ["monday", "SMALLINT"],
            ["tuesday", "SMALLINT"],
            ["wednesday", "SMALLINT"],
            ["thursday", "SMALLINT"],
            ["friday", "SMALLINT"],
            ["saturday", "SMALLINT"],
            ["sunday", "SMALLINT"],
            ["start_date", "INT"],
            ["end_date", "INT"],
        ],
    },
    // {
    //     name: `occupancies`,
    //     file: `occupancies.txt`,
    //     columns: [
    //         ["trip_id", "CITEXT"],
    //         ["stop_sequence", "SMALLINT"],
    //         ["occupancy_status", "SMALLINT"],
    //         ["monday", "SMALLINT"],
    //         ["tuesday", "SMALLINT"],
    //         ["wednesday", "SMALLINT"],
    //         ["thursday", "SMALLINT"],
    //         ["friday", "SMALLINT"],
    //         ["saturday", "SMALLINT"],
    //         ["sunday", "SMALLINT"],
    //         ["start_date", "INT"],
    //         ["end_date", "INT"],
    //         ["exception", "BOOLEAN"],
    //     ],
    // },
    {
        name: `calendar_dates`,
        file: `calendar_dates.txt`,
        columns: [
            ["service_id", "CITEXT"],
            ["date", "INT"],
            ["exception_type", "INT"],
        ],
    },
    // {
    //     name: "vehicle_boardings",
    //     file: `vehicle_boardings.txt`,
    //     columns: [
    //         ["vehicle_category_id", "CITEXT"],
    //         ["child_sequence", "SMALLINT"],
    //         ["grandchild_sequence", "SMALLINT"],
    //         ["boarding_area_id", "CITEXT"],
    //     ],
    // },
    {
        name: "vehicle_categories",
        file: `vehicle_categories.txt`,
        columns: [
            ["vehicle_category_id", "CITEXT"],
            ["vehicle_category_name", "CITEXT"],
        ],
    },
    // {
    //     name: "vehicle_couplings",
    //     file: `vehicle_couplings.txt`,
    //     columns: [
    //         ["parent_id", "CITEXT"],
    //         ["child_id", "CITEXT"],
    //         ["child_sequence", "CITEXT"],
    //         ["child_label", "CITEXT"],
    //     ],
    // },
    // {
    //     name: `pathways`,
    //     file: `pathways.txt`,
    //     columns: [
    //         ["pathway_id", "CITEXT PRIMARY KEY"],
    //         ["from_stop_id", "CITEXT"],
    //         ["to_stop_id", "CITEXT"],
    //         ["pathway_mode", "SMALLINT"],
    //         ["is_bidirectional", "SMALLINT"],
    //         ["traversal_time", "SMALLINT"],
    //     ],
    // },
    // {
    //     name: `levels`,
    //     file: `levels.txt`,
    //     columns: [
    //         ["level_id", "CITEXT"],
    //         ["level_index", "SMALLINT"],
    //         ["level_name", "CITEXT"],
    //     ],
    // },
];

export default tables;
